/* automatically generated by configure. */

#define HAVE_GETOPT 1
#define HAVE_INET_PTON_NTOP 1
#define HAVE_IPv6 1
#define HAVE_POLL 1
#define HAVE_ETC_RESOLV_CONF 1
#define HAVE_RES_INIT 1

#undef HAVE_FOPEN_S
#undef HAVE_REGKEY
#undef HAVE_IPHLPAPI_H
#undef HAVE_DUPENV_S
#undef HAVE_STRTOK_S
#undef HAVE_SPRINTF_S
#undef HAVE_STRERROR_S
#undef HAVE_GMTIME_S
#undef HAVE_DHCPREQUESTPARAMS
#undef HAVE_DHCPV6REQUESTPARAMS
